### ISSUE TITLE
Possible wrong CID

### ISSUE THREAD

**Issue by richardschneider** [ipld/js-ipld-zcash#13]
Looking at the code for `util.cid` I see that the multihash is created from `dagNode.header` not `dagNode` like all the other IPLD packages.

This implies that the hash of the serialised block is not the same hash that is generated by `util.cid`; which  BREAKS https://github.com/ipld/interface-ipld-format/issues/32

@vmx any comments?

**Comment by vmx** [comment]
That's actually a really good point (BTW: it's the same for Bitcoin). The reason for it is, that we want to have the same hash as Zcash is generating. This violates how IPLD is supposed to work. I need to put more thought into this and play around a bit with some actual data, to see if it really is an issue.

**Comment by richardschneider** [comment]
Are you sure about Bitcoin?  My reading of the code says that it is okay.

**Comment by vmx** [comment]
@richardschneider You are right, js-ipld-bitcoin does it differently, but I think it's wrong. I really need to dig into this.

**Comment by richardschneider** [comment]
I think ethereum might have a similar issue.

**Comment by vmx** [comment]
Follow up issues for this one are

 - https://github.com/ipld/js-ipld-zcash/issues/14
 - https://github.com/ipld/js-ipld-bitcoin/issues/21

Ethereum already distinguishes between the different blocks.

Thanks @richardschneider for pointing this out.

**Comment by vmx** [comment]
Closing this issue in favour of:

 - https://github.com/ipld/js-ipld-zcash/issues/19
 - https://github.com/ipld/js-ipld-bitcoin/issues/25
