### ISSUE TITLE
dependency on dirty-chai

### ISSUE THREAD

**Issue by mitra42** [ipld/js-ipld-zcash#22]
Is there a reason that js-ipld-zcash has a dependency on dirty-chai ? 

In every other module I can find its a devDependency rather than a dependency.

The reason it matters ... dirty-chai has a peer dependency on chai, which means that `npm install` generates an error, meaning you can't do a clean install if you include ipfs which requires ipld which requires ipld-zcash.

**Comment by vmx** [comment]
There is no reason, I just overlooked it when I created this module. It would be cool if you could submit a Pull Request fixing the dependencies.

**Comment by mitra42** [comment]
Done

**Comment by mitra42** [comment]
Ok - can you make the change, I did it as a courtesy on your request, but you've declined to integrate it.. 

I have no way to test this, have no interaction with this module other than it generating a bug, and of course had no knowledge of your commit format, nor interest in learning your format it as I'm highly unlikely to ever interact with the module again - the only reason I know of its existence is because it generates an error when its included in IPFS.

**Comment by vmx** [comment]
Thanks a lot for doing the PR. I'll take it from there.

**Comment by vmx** [comment]
This was fixed with https://github.com/ipld/js-ipld-zcash/pull/23 (sorry I forgot to mention it in the commit message) and released with version 0.1.6.
