### ISSUE TITLE
Deprecated zcash-bitcore-lib containes an outdated lodash with security vulnerability

### ISSUE THREAD

**Issue by noman-land** [ipld/js-ipld-zcash#24]
I'm getting a few low severity security warnings from `npm audit` for [ipfs@0.32.1](https://www.npmjs.com/package/ipfs/v/0.32.1) because this lib is using a deprecated `zcash-bitcore-lib` ([npm](https://www.npmjs.com/package/zcash-bitcore-lib)) ([github](https://github.com/BitMEX/zcash-bitcore-lib)) which has an old version of lodash in it.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/27938023/45731946-0ce47a00-bba8-11e8-9433-5f6e11e8d754.png">

Would you consider using a more up to date fork that has a newer lodash? It appears that versions >=4.17.5 have resolved this issue.

**Comment by vmx** [comment]
If there's a Zcash library, I'm happy to switch to another one.

**Comment by vmx** [comment]
@noman-land Sorry I didn't follow the links. I wasn't aware that the library we were using was officially deprecated. It's cool that it links to another (https://github.com/zcash-hackworks/bitcore-lib-zcash). If anyone wants to give that one a spin, PRs are welcome :)

**Comment by noman-land** [comment]
I don't know if I'd feel comfortable making the changes it but it's worth mentioning that the lib you linked to also has an outdated version of lodash 🤦‍♂️ .

**Comment by vmx** [comment]
I spent a bit of time to find a library that can parse Zcash blocks/transactions that has working tests. I couldn't find any. So if anyone has/finds one, please let me know.

**Comment by vmx** [comment]
With https://github.com/ipld/js-ipld-zcash/pull/46 merged we no longer use zcash-bitcore-lib.
